# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'win11'  # 생성한 에이전트 풀 이름

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UiPathInstallPlatform@4
  inputs:
    cliVersion: 'WIN_23.10.8753.32995'
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'fdxcom'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Verbose'
    
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'fdxcom'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'CICD_TEST'
    traceLevel: 'Verbose'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
